module.exports = {
  TEMPLATES_PATH: "templates",
  templates: [
    {
      name: "DAO-Cameligo",
      category: "governance",
      repository: "https://github.com/ligolang/dao-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of DAO contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "DAO-Jsligo",
      category: "governance",
      repository: "https://github.com/ligolang/dao-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of DAO contract in JsLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Multisig-Cameligo",
      category: "governance",
      repository: "https://github.com/ligolang/multisig-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of multisig contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Multisig-Jsligo",
      category: "governance",
      repository: "https://github.com/ligolang/multisig-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of multisig contract in JsLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "NFT-Factory-Cameligo",
      category: "token",
      repository: "https://github.com/ligolang/NFT-factory-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of a NFT Factory contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "NFT-Factory-JsLIGO",
      category: "token",
      repository: "https://github.com/ligolang/NFT-factory-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of a NFT Factory contract in JsLIGO Resources",
      readme: "",
      endpoints: [],
    },
    {
      name: "Permit-Cameligo",
      category: "token",
      repository: "https://github.com/ligolang/permit-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of a permit contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Permit-JsLIGO",
      category: "token",
      repository: "https://github.com/ligolang/permit-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of a permit contract in JsLIGO Resources",
      readme: "",
      endpoints: [],
    },
    {
      name: "Advisor-Cameligo",
      category: "utilities",
      repository: "https://github.com/ligolang/advisor-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of an advisor contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Advisor-JSLigo",
      category: "utilities",
      repository: "https://github.com/ligolang/advisor-jsligo/",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of an advisor contract in JSLigo",
      readme: "",
      endpoints: [],
    },
    {
      name: "Randomness-Cameligo",
      category: "utilities",
      repository: "https://github.com/ligolang/randomness-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "Exemple of a NFT Factory contract in CameLIGO ",
      readme: "",
      endpoints: [],
    },
    {
      name: "Randomness-JsLIGO",
      category: "utilities",
      repository: "https://github.com/ligolang/randomness-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description:
        "An exemple of a contract generating a random number in JsLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Shifumi-Cameligo",
      category: "token",
      repository: "https://github.com/ligolang/shifumi-cameligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of a shifumi game contract in CameLIGO",
      readme: "",
      endpoints: [],
    },
    {
      name: "Shifumi-Jsligo",
      category: "utilities",
      repository: "https://github.com/ligolang/shifumi-jsligo",
      author: { name: "LIGO" },
      version: "1.0",
      description: "An exemple of a shifumi game contract in JsLIGO",
      readme: "",
      endpoints: [],
    },
  ],
};
