name: Docker CI

on:
  push:
    branches:
      - "main"
  pull_request:
    tags:
      - docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: "Docker build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push release version
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/marigold-dev/ligo-registry:stable
            ghcr.io/marigold-dev/ligo-registry:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push preprod version
        if: ${{ contains(github.event.pull_request.labels.*.name, 'docker') }}
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/marigold-dev/ligo-registry:preprod
          cache-from: type=gha
          cache-to: type=gha,mode=max
